#ifndef _TLN2000AP_H_
#define _TLN2000AP_H_

#include <stdlib.h>

#include "greatCircle.h"
#include "state.h"
#include "tln_structs.h"

extern tln_sm_transition_t states[];
extern tln_sm_t tln2000sm;

enum {
    TLN_STATE_OFF = TLN_USER_STATES_START,
    TLN_STATE_SELF_TEST_START,
    TLN_STATE_SELF_TEST,
    TLN_STATE_FUEL_ON_BOARD_PROMPT,
    TLN_STATE_FUEL_ON_BOARD_EDIT,
    TLN_STATE_READY_FOR_NAV,

    // NAV
    TLN_STATE_NAV,
    TLN_STATE_NAV_DES,

    // WPT
    TLN_STATE_WPT,
    TLN_STATE_WPT_SELECT,
    TLN_STATE_WPT_CATEGORY,
    TLN_STATE_WPT_AIRPORT,
    TLN_STATE_WPT_VOR,
    TLN_STATE_WPT_NDB,
    TLN_STATE_WPT_INT,
    TLN_STATE_WPT_USER,

    // CALC
    TLN_STATE_CALC,
    TLN_STATE_CALC_EDIT,
    TLN_STATE_CALC_PPOS_SAVE,

    TLN_STATE_AUX_CHECKLIST,
    TLN_STATE_AUX_SYSTEM_STATUS,
    TLN_STATE_AUX_SENSOR_STATUS,
    TLN_STATE_AUX_CONFIGURE,
    TLN_STATE_AUX_SETUP,
    TLN_STATE_AUX_STATUS,
    TLN_STATE_AUX_VOLTTEMP,
    TLN_STATE_AUX_DATABASE_EXP,
    TLN_STATE_AUX_SOFT_REV,
    TLN_STATE_AUX_SOFT_CODE,

    // APTVOR
    TLN_STATE_APTVOR,
    TLN_STATE_APTVOR_CATEGORY,
} TLN_STATE;

enum {
    // Generic update Event
    TLN_EVENT_UPDATE = TLN_USER_EVENTS_START,
    TLN_EVENT_SYSTEM_UPDATE,
    TLN_EVENT_TIMEOUT,

    // Self test event
    TLN_EVENT_TEST_PASS,
    TLN_EVENT_LCD_ON,

    // SD Card
    TLN_EVENT_SDCARD_REMOVE,
    TLN_EVENT_SDCARD_INSERT,

    // Mode key-press events
    TLN_EVENT_BTN_POWER,
    TLN_EVENT_BTN_NAV,
    TLN_EVENT_BTN_NAV_HOLD,
    TLN_EVENT_BTN_WPT,
    TLN_EVENT_BTN_WPT_HOLD,
    TLN_EVENT_BTN_FPL,
    TLN_EVENT_BTN_FPL_HOLD,
    TLN_EVENT_BTN_CALC,
    TLN_EVENT_BTN_CALC_HOLD,
    TLN_EVENT_BTN_AUX,
    TLN_EVENT_BTN_AUX_HOLD,
    TLN_EVENT_BTN_APTVOR,
    TLN_EVENT_BTN_APTVOR_HOLD,

    // Function key presses
    TLN_EVENT_BTN_DIRECT,
    TLN_EVENT_BTN_MSG,
    TLN_EVENT_BTN_ENT,

    // Control wheel
    TLN_EVENT_BTN_ROT_OUT_CW,
    TLN_EVENT_BTN_ROT_OUT_CC,
    TLN_EVENT_BTN_ROT_IN_CW,
    TLN_EVENT_BTN_ROT_IN_CC
} TLN_EVENT;

tln_sm_t init_tln2000();

#endif  // _TLN2000_H_